const mockData = [
    {
        link: '#',
        avatar: 'https://via.placeholder.com/150',
        name: 'John Doe',
        message: 'Hello, how are you?',
        time: '12:00',
        messageCounter: 0,
    },
    {
        avatar: 'https://via.placeholder.com/150',
        name: 'John Doe',
        message: 'И Human Interface Guidelines и Material Design рекомендуют делать так а не иначе',
        time: '12:00',
        'unread_count': 0,
    },
    {
        avatar: '',
        name: 'John Doe',
        message: 'Hello, how are you?',
        time: '12:00',
        messageCounter: 10,
    },
    {
        avatar: 'https://via.placeholder.com/150',
        name: 'John Doe',
        message: 'Hello, how are you?',
        time: '12:00',
        messageCounter: 0,
    },
    {
        avatar: 'https://via.placeholder.com/150',
        name: 'John Doe',
        message: 'Hello, how are you?',
        time: '12:00',
        messageCounter: 0,
    },
    {
        link: '#',
        avatar: 'https://via.placeholder.com/150',
        name: 'John Doe',
        message: 'Hello, how are you?',
        time: '12:00',
        messageCounter: 0,
    },
    {
        avatar: 'https://via.placeholder.com/150',
        name: 'John Doe',
        message: 'И Human Interface Guidelines и Material Design рекомендуют делать так а не иначе',
        time: '12:00',
        messageCounter: 0,
    },
    {
        avatar: '',
        name: 'John Doe',
        message: 'Hello, how are you?',
        time: '12:00',
        messageCounter: 10,
    },
    {
        avatar: 'https://via.placeholder.com/150',
        name: 'John Doe',
        message: 'Hello, how are you?',
        time: '12:00',
        messageCounter: 0,
    },
    {
        avatar: 'https://via.placeholder.com/150',
        name: 'John Doe',
        message: 'Hello, how are you?',
        time: '12:00',
        messageCounter: 0,
    },
    {
        link: '#',
        avatar: 'https://via.placeholder.com/150',
        name: 'John Doe',
        message: 'Hello, how are you?',
        time: '12:00',
        messageCounter: 0,
    },
    {
        avatar: 'https://via.placeholder.com/150',
        name: 'John Doe',
        message: 'И Human Interface Guidelines и Material Design рекомендуют делать так а не иначе',
        time: '12:00',
        messageCounter: 0,
    },
    {
        avatar: '',
        name: 'John Doe',
        message: 'Hello, how are you?',
        time: '12:00',
        messageCounter: 10,
    },
    {
        avatar: 'https://via.placeholder.com/150',
        name: 'John Doe',
        message: 'Hello, how are you?',
        time: '12:00',
        messageCounter: 0,
    },
    {
        avatar: 'https://via.placeholder.com/150',
        name: 'John Doe',
        message: 'Hello, how are you?',
        time: '12:00',
        messageCounter: 0,
    },
    {
        link: '#',
        avatar: 'https://via.placeholder.com/150',
        name: 'John Doe',
        message: 'Hello, how are you?',
        time: '12:00',
        messageCounter: 0,
    },
    {
        avatar: 'https://via.placeholder.com/150',
        name: 'John Doe',
        message: 'И Human Interface Guidelines и Material Design рекомендуют делать так а не иначе',
        time: '12:00',
        messageCounter: 0,
    },
    {
        avatar: '',
        name: 'John Doe',
        message: 'Hello, how are you?',
        time: '12:00',
        messageCounter: 10,
    },
    {
        avatar: 'https://via.placeholder.com/150',
        name: 'John Doe',
        message: 'Hello, how are you?',
        time: '12:00',
        messageCounter: 0,
    },
    {
        avatar: 'https://via.placeholder.com/150',
        name: 'John Doe',
        message: 'Hello, how are you?',
        time: '12:00',
        messageCounter: 0,
    },
]

export default mockData;
